---
- name: install required packages
  apt: name={{item}}
  with_items:
    - qemu-kvm
    - libvirt-bin
    - python-libvirt
    - python-lxml
    - daemon

- name: ensure that libvirtd has been started correctly
  service: name=libvirtd state=started enabled=yes

- name: create directory for iso and vms
  file: path=/data/{{item}} state=directory
  with_items:
    - iso
    - vms

- name: download netinst iso for jessie
  get_url:
    url: https://mirrors.tuna.tsinghua.edu.cn/debian-cd/8.6.0/amd64/iso-cd/debian-8.6.0-amd64-netinst.iso
    dest: /data/iso/
    checksum: sha256:9479c5c2df72ae3878116c43fb42eefae53d1fe363ce514a6afc8289064b9f5f
  notify:
    - refresh pool for iso

- name: download initrd and kernel for installer
  get_url:
    url: https://mirrors.tuna.tsinghua.edu.cn/debian/dists/jessie/main/installer-amd64/current/images/cdrom/{{item}}
    dest: /data/iso/
  with_items:
    - vmlinuz
    - initrd.gz
  notify:
    - refresh pool for iso

- name: create volume for guest
  qemu_img: dest=/data/vms/shared-guest.qcow2 size=102400
  notify:
    - refresh pool for vms

- name: define pools for iso and vms
  virt_pool: name="{{item}}" command=define xml='{{ lookup("template", "pool-dir.xml.j2") }}'
  with_items:
    - iso
    - vms

- name: start pools
  virt_pool: name="{{item}}" state=active
  with_items:
    - iso
    - vms

- name: enable pools
  virt_pool: name="{{item}}" autostart=yes
  with_items:
    - iso
    - vms

- name: define nat network
  virt_net: name=nat command=define xml='{{ lookup("template", "net-nat.xml.j2") }}'

- name: start nat network
  virt_net: name=nat state=active

- name: enable nat network
  virt_net: name=nat autostart=yes

- name: create directory for preseeds
  file: path=/tmp/preseeds state=directory mode="u=rwx,g=,o="

- name: upload preseed
  template: src=preseed.j2 dest=/tmp/preseeds/preseed-shared-guest.txt mode="u=rw,g=,o="

- name: define the guest
  virt: name="shared-guest" command=define xml='{{ lookup("template", "domain-kvm.xml.j2") }}'
