---
- hosts: kvm-host
  become: yes
  pre_tasks:
    - assert:
        that:
          - "ansible_distribution == 'Debian'"
          - "ansible_distribution_major_version == '8'"
          - "ansible_architecture == 'x86_64'"

  roles:
    - kvm
