---
- name: enable backports
  apt_repository: repo='deb http://mirrors.tuna.tsinghua.edu.cn/debian jessie-backports main contrib non-free'

- name: install required packages
  apt: name={{item}}
  with_items:
    - nslcd
    - nscd
    - git
    - golang-1.6

- name: download and install tunaccount
  command: /usr/lib/go-1.6/bin/go get github.com/tuna/tunaccount
  environment:
    GOPATH: /opt/tunaccount

- name: upload configuration for tunaccount
  template: src=tunaccountd.j2 dest=/etc/tunaccountd.conf

- name: install service for tunaccountd
  template: src=tunaccountd.service.j2 dest=/etc/systemd/system/tunaccountd.service

- name: remove default base in configuration of nslcd
  lineinfile:
    line: base dc=example,dc=net
    dest: /etc/nslcd.conf
    state: absent
  notify:
    - restart nslcd and nscd

- name: set correct base according to README of tunaccount
  blockinfile:
    dest: /etc/nslcd.conf
    block: |
      base o=tuna
      base passwd ou=people,o=tuna
      base shadow ou=people,o=tuna
      base group ou=groups,o=tuna
  notify:
    - restart nslcd and nscd

- name: start and enable nslcd and nscd
  service: name={{item}} state=started enabled=yes
  with_items:
    - nslcd
    - nscd

- name: configure nsswitch
  lineinfile:
    line: "{{item}}:         files ldap"
    dest: /etc/nsswitch.conf
    regexp: "^{{item}}:.*$"
  with_items:
    - passwd
    - group
    - shadow

- name: config pam to make home for users
  lineinfile:
    line: session required        pam_mkhomedir.so        skel=/etc/skel  umask=0022
    dest: /etc/pam.d/common-session

- name: install additional packages for users
  apt: name={{item}}
  with_items:
    - zsh
    - vim
    - tmux

# This should be at the bottom or given password may not working
- name: enable and start tunaccount
  service: name=tunaccountd state=started enabled=yes
