---
- hosts: kvm-host
  become: yes
  vars_prompt:
    - name: "confirm"
      prompt: "This playbook will ERASE pre-installed vm, are you sure?(type YES)"
  pre_tasks:
    - assert:
        that:
          - "ansible_distribution == 'CentOS'"
          - "ansible_distribution_major_version == '7'"
          - "ansible_architecture == 'x86_64'"
          - "confirm == 'YES'"

  roles:
    - kvm
